// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYFokioX7u_qak6INeNfZeutUqWrZR-l4',
    appId: '1:259936288609:web:5390aef6dab066a02a8f20',
    messagingSenderId: '259936288609',
    projectId: 'hoodcast-c30ce',
    authDomain: 'hoodcast-c30ce.firebaseapp.com',
    storageBucket: 'hoodcast-c30ce.firebasestorage.app',
    measurementId: 'G-FRE4XSSGP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdyOiQdx1hsIyejmkOvrL4jToopWWEJn0',
    appId: '1:259936288609:android:f361aeea3c4505fc2a8f20',
    messagingSenderId: '259936288609',
    projectId: 'hoodcast-c30ce',
    storageBucket: 'hoodcast-c30ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4lZ5of_97I8EViTlum_-o_NPxwTlAvkE',
    appId: '1:259936288609:ios:8c56de657232e11e2a8f20',
    messagingSenderId: '259936288609',
    projectId: 'hoodcast-c30ce',
    storageBucket: 'hoodcast-c30ce.firebasestorage.app',
    iosBundleId: 'com.example.clientFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4lZ5of_97I8EViTlum_-o_NPxwTlAvkE',
    appId: '1:259936288609:ios:8c56de657232e11e2a8f20',
    messagingSenderId: '259936288609',
    projectId: 'hoodcast-c30ce',
    storageBucket: 'hoodcast-c30ce.firebasestorage.app',
    iosBundleId: 'com.example.clientFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYFokioX7u_qak6INeNfZeutUqWrZR-l4',
    appId: '1:259936288609:web:f54fdc7bd91644b42a8f20',
    messagingSenderId: '259936288609',
    projectId: 'hoodcast-c30ce',
    authDomain: 'hoodcast-c30ce.firebaseapp.com',
    storageBucket: 'hoodcast-c30ce.firebasestorage.app',
    measurementId: 'G-XFFKFV58J3',
  );
}
