create extension if not exists "postgis" with schema "extensions";


create table "public"."alerts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint,
    "tier" bigint,
    "category" text not null default 'community'::text,
    "title" text,
    "body" text,
    "status" text default 'pending'::text,
    "published_at" timestamp with time zone,
    "location" geography not null,
    "radius_m" bigint,
    "flagged" boolean not null default false
);


alter table "public"."alerts" enable row level security;

create table "public"."alerts_verifications" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint,
    "alert_id" bigint,
    "verified" boolean default true
);


alter table "public"."alerts_verifications" enable row level security;

create table "public"."roles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "role" text default 'citizen'::text
);


alter table "public"."roles" enable row level security;

create table "public"."tiers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "tier" text default ''::text,
    "priority" text default 'low'::text
);


alter table "public"."tiers" enable row level security;

create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "first_name" text,
    "last_name" text,
    "role" bigint,
    "age" bigint default '16'::bigint,
    "is_age_verified" boolean default false,
    "rep_score" bigint default '0'::bigint,
    "location" geography,
    "location_updated_at" timestamp with time zone,
    "auth_id" uuid,
    "username" text not null,
    "preferred_radius_m" bigint not null default '2000'::bigint
);


alter table "public"."users" enable row level security;

create table "public"."users_devices" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" bigint,
    "fcm_token" text not null,
    "platform" text,
    "updated_at" timestamp with time zone
);


alter table "public"."users_devices" enable row level security;

create table "public"."users_received_alerts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "receiver_id" bigint,
    "alert_id" bigint
);


alter table "public"."users_received_alerts" enable row level security;

CREATE UNIQUE INDEX alerts_pkey ON public.alerts USING btree (id);

CREATE UNIQUE INDEX alerts_verifications_pkey ON public.alerts_verifications USING btree (id);

CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (id);

CREATE UNIQUE INDEX tiers_pkey ON public.tiers USING btree (id);

CREATE UNIQUE INDEX users_devices_fcm_token_key ON public.users_devices USING btree (fcm_token);

CREATE UNIQUE INDEX users_devices_pkey ON public.users_devices USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX users_received_alerts_pkey ON public.users_received_alerts USING btree (id);

CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username);

alter table "public"."alerts" add constraint "alerts_pkey" PRIMARY KEY using index "alerts_pkey";

alter table "public"."alerts_verifications" add constraint "alerts_verifications_pkey" PRIMARY KEY using index "alerts_verifications_pkey";

alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "public"."tiers" add constraint "tiers_pkey" PRIMARY KEY using index "tiers_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."users_devices" add constraint "users_devices_pkey" PRIMARY KEY using index "users_devices_pkey";

alter table "public"."users_received_alerts" add constraint "users_received_alerts_pkey" PRIMARY KEY using index "users_received_alerts_pkey";

alter table "public"."alerts" add constraint "alerts_tier_fkey" FOREIGN KEY (tier) REFERENCES tiers(id) not valid;

alter table "public"."alerts" validate constraint "alerts_tier_fkey";

alter table "public"."alerts" add constraint "alerts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."alerts" validate constraint "alerts_user_id_fkey";

alter table "public"."alerts_verifications" add constraint "alerts_verifications_alert_id_fkey" FOREIGN KEY (alert_id) REFERENCES alerts(id) not valid;

alter table "public"."alerts_verifications" validate constraint "alerts_verifications_alert_id_fkey";

alter table "public"."alerts_verifications" add constraint "alerts_verifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."alerts_verifications" validate constraint "alerts_verifications_user_id_fkey";

alter table "public"."users" add constraint "users_auth_id_fkey" FOREIGN KEY (auth_id) REFERENCES auth.users(id) not valid;

alter table "public"."users" validate constraint "users_auth_id_fkey";

alter table "public"."users" add constraint "users_role_fkey" FOREIGN KEY (role) REFERENCES roles(id) not valid;

alter table "public"."users" validate constraint "users_role_fkey";

alter table "public"."users" add constraint "users_username_key" UNIQUE using index "users_username_key";

alter table "public"."users_devices" add constraint "users_devices_fcm_token_key" UNIQUE using index "users_devices_fcm_token_key";

alter table "public"."users_devices" add constraint "users_devices_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."users_devices" validate constraint "users_devices_user_id_fkey";

alter table "public"."users_received_alerts" add constraint "users_received_alerts_alert_id_fkey" FOREIGN KEY (alert_id) REFERENCES alerts(id) not valid;

alter table "public"."users_received_alerts" validate constraint "users_received_alerts_alert_id_fkey";

alter table "public"."users_received_alerts" add constraint "users_received_alerts_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES users(id) not valid;

alter table "public"."users_received_alerts" validate constraint "users_received_alerts_receiver_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_alert_location(p_alert_id bigint)
 RETURNS TABLE(alert_id bigint, latitude double precision, longitude double precision)
 LANGUAGE sql
 STABLE
AS $function$
  select
    a.id as alert_id,
    st_y(a.location::geometry) as latitude,
    st_x(a.location::geometry) as longitude
  from public.alerts a
  where a.id = p_alert_id
  limit 1;
$function$
;

CREATE OR REPLACE FUNCTION public.get_alert_recipient_user_ids(p_alert_id bigint)
 RETURNS TABLE(user_id bigint, distance_m double precision)
 LANGUAGE sql
 STABLE
AS $function$
  select
    u.id as user_id,
    st_distance(u.location, a.location) as distance_m
  from public.alerts a
  join public.users u on u.id <> a.user_id
  where a.id = p_alert_id
    and a.location is not null
    and u.location is not null
    and st_dwithin(
      u.location,
      a.location,
      greatest(coalesce(u.preferred_radius_m, 0), 0)
        + greatest(coalesce(a.radius_m, 0), 0)
    );
$function$
;

CREATE OR REPLACE FUNCTION public.get_alerts_in_map_bounds(p_south_lat double precision, p_west_lng double precision, p_north_lat double precision, p_east_lng double precision, p_limit integer DEFAULT 200)
 RETURNS TABLE(alert_id bigint, title text, body text, category text, status text, flagged boolean, user_id bigint, tier integer, radius_m integer, created_at timestamp with time zone, published_at timestamp with time zone, latitude double precision, longitude double precision)
 LANGUAGE sql
 STABLE
AS $function$
  with normalized_bounds as (
    select
      least(p_south_lat, p_north_lat) as south_lat,
      greatest(p_south_lat, p_north_lat) as north_lat,
      p_west_lng as west_lng,
      p_east_lng as east_lng,
      greatest(coalesce(p_limit, 200), 1) as result_limit
  )
  select
    a.id as alert_id,
    a.title,
    a.body,
    a.category,
    a.status,
    a.flagged,
    a.user_id,
    a.tier,
    a.radius_m,
    a.created_at,
    a.published_at,
    st_y(a.location::geometry) as latitude,
    st_x(a.location::geometry) as longitude
  from public.alerts a
  cross join normalized_bounds b
  where a.location is not null
    and a.status = 'published'
    and st_y(a.location::geometry) between b.south_lat and b.north_lat
    and (
      (b.west_lng <= b.east_lng and st_x(a.location::geometry) between b.west_lng and b.east_lng)
      or
      (b.west_lng > b.east_lng and (
        st_x(a.location::geometry) >= b.west_lng
        or st_x(a.location::geometry) <= b.east_lng
      ))
    )
  order by coalesce(a.published_at, a.created_at) desc
  limit (select result_limit from normalized_bounds);
$function$
;

CREATE OR REPLACE FUNCTION public.parse_location_binary(p_location text)
 RETURNS TABLE(latitude double precision, longitude double precision)
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
declare
  g geometry;
  clean text;
begin
  clean := trim(p_location);

  if clean is null or clean = '' then
    return;
  end if;

  -- Hex EWKB with \x prefix
  if clean ~* '^\\x[0-9a-f]+$' then
    clean := substr(clean, 3);
    g := st_geomfromewkb(decode(clean, 'hex'));

  -- Hex EWKB without prefix
  elsif clean ~* '^[0-9a-f]+$' then
    g := st_geomfromewkb(decode(clean, 'hex'));

  -- Optional fallback for WKT input
  elsif clean ~* '^(point|linestring|polygon|multipoint|multilinestring|multipolygon|geometrycollection)\\s*\\(' then
    g := st_geomfromtext(clean, 4326);

  else
    raise exception 'Unsupported location format: %', clean;
  end if;

  if st_srid(g) = 0 then
    g := st_setsrid(g, 4326);
  end if;

  latitude := st_y(g);
  longitude := st_x(g);
  return next;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.parse_location_wkt(p_location_text text)
 RETURNS TABLE(latitude double precision, longitude double precision)
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select
    st_y(st_geomfromtext(p_location_text, 4326)) as latitude,
    st_x(st_geomfromtext(p_location_text, 4326)) as longitude;
$function$
;

grant delete on table "public"."alerts" to "anon";

grant insert on table "public"."alerts" to "anon";

grant references on table "public"."alerts" to "anon";

grant select on table "public"."alerts" to "anon";

grant trigger on table "public"."alerts" to "anon";

grant truncate on table "public"."alerts" to "anon";

grant update on table "public"."alerts" to "anon";

grant delete on table "public"."alerts" to "authenticated";

grant insert on table "public"."alerts" to "authenticated";

grant references on table "public"."alerts" to "authenticated";

grant select on table "public"."alerts" to "authenticated";

grant trigger on table "public"."alerts" to "authenticated";

grant truncate on table "public"."alerts" to "authenticated";

grant update on table "public"."alerts" to "authenticated";

grant delete on table "public"."alerts" to "service_role";

grant insert on table "public"."alerts" to "service_role";

grant references on table "public"."alerts" to "service_role";

grant select on table "public"."alerts" to "service_role";

grant trigger on table "public"."alerts" to "service_role";

grant truncate on table "public"."alerts" to "service_role";

grant update on table "public"."alerts" to "service_role";

grant delete on table "public"."alerts_verifications" to "anon";

grant insert on table "public"."alerts_verifications" to "anon";

grant references on table "public"."alerts_verifications" to "anon";

grant select on table "public"."alerts_verifications" to "anon";

grant trigger on table "public"."alerts_verifications" to "anon";

grant truncate on table "public"."alerts_verifications" to "anon";

grant update on table "public"."alerts_verifications" to "anon";

grant delete on table "public"."alerts_verifications" to "authenticated";

grant insert on table "public"."alerts_verifications" to "authenticated";

grant references on table "public"."alerts_verifications" to "authenticated";

grant select on table "public"."alerts_verifications" to "authenticated";

grant trigger on table "public"."alerts_verifications" to "authenticated";

grant truncate on table "public"."alerts_verifications" to "authenticated";

grant update on table "public"."alerts_verifications" to "authenticated";

grant delete on table "public"."alerts_verifications" to "service_role";

grant insert on table "public"."alerts_verifications" to "service_role";

grant references on table "public"."alerts_verifications" to "service_role";

grant select on table "public"."alerts_verifications" to "service_role";

grant trigger on table "public"."alerts_verifications" to "service_role";

grant truncate on table "public"."alerts_verifications" to "service_role";

grant update on table "public"."alerts_verifications" to "service_role";

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant delete on table "public"."roles" to "authenticated";

grant insert on table "public"."roles" to "authenticated";

grant references on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "authenticated";

grant trigger on table "public"."roles" to "authenticated";

grant truncate on table "public"."roles" to "authenticated";

grant update on table "public"."roles" to "authenticated";

grant delete on table "public"."roles" to "service_role";

grant insert on table "public"."roles" to "service_role";

grant references on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "service_role";

grant trigger on table "public"."roles" to "service_role";

grant truncate on table "public"."roles" to "service_role";

grant update on table "public"."roles" to "service_role";

grant delete on table "public"."tiers" to "anon";

grant insert on table "public"."tiers" to "anon";

grant references on table "public"."tiers" to "anon";

grant select on table "public"."tiers" to "anon";

grant trigger on table "public"."tiers" to "anon";

grant truncate on table "public"."tiers" to "anon";

grant update on table "public"."tiers" to "anon";

grant delete on table "public"."tiers" to "authenticated";

grant insert on table "public"."tiers" to "authenticated";

grant references on table "public"."tiers" to "authenticated";

grant select on table "public"."tiers" to "authenticated";

grant trigger on table "public"."tiers" to "authenticated";

grant truncate on table "public"."tiers" to "authenticated";

grant update on table "public"."tiers" to "authenticated";

grant delete on table "public"."tiers" to "service_role";

grant insert on table "public"."tiers" to "service_role";

grant references on table "public"."tiers" to "service_role";

grant select on table "public"."tiers" to "service_role";

grant trigger on table "public"."tiers" to "service_role";

grant truncate on table "public"."tiers" to "service_role";

grant update on table "public"."tiers" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

grant delete on table "public"."users_devices" to "anon";

grant insert on table "public"."users_devices" to "anon";

grant references on table "public"."users_devices" to "anon";

grant select on table "public"."users_devices" to "anon";

grant trigger on table "public"."users_devices" to "anon";

grant truncate on table "public"."users_devices" to "anon";

grant update on table "public"."users_devices" to "anon";

grant delete on table "public"."users_devices" to "authenticated";

grant insert on table "public"."users_devices" to "authenticated";

grant references on table "public"."users_devices" to "authenticated";

grant select on table "public"."users_devices" to "authenticated";

grant trigger on table "public"."users_devices" to "authenticated";

grant truncate on table "public"."users_devices" to "authenticated";

grant update on table "public"."users_devices" to "authenticated";

grant delete on table "public"."users_devices" to "service_role";

grant insert on table "public"."users_devices" to "service_role";

grant references on table "public"."users_devices" to "service_role";

grant select on table "public"."users_devices" to "service_role";

grant trigger on table "public"."users_devices" to "service_role";

grant truncate on table "public"."users_devices" to "service_role";

grant update on table "public"."users_devices" to "service_role";

grant delete on table "public"."users_received_alerts" to "anon";

grant insert on table "public"."users_received_alerts" to "anon";

grant references on table "public"."users_received_alerts" to "anon";

grant select on table "public"."users_received_alerts" to "anon";

grant trigger on table "public"."users_received_alerts" to "anon";

grant truncate on table "public"."users_received_alerts" to "anon";

grant update on table "public"."users_received_alerts" to "anon";

grant delete on table "public"."users_received_alerts" to "authenticated";

grant insert on table "public"."users_received_alerts" to "authenticated";

grant references on table "public"."users_received_alerts" to "authenticated";

grant select on table "public"."users_received_alerts" to "authenticated";

grant trigger on table "public"."users_received_alerts" to "authenticated";

grant truncate on table "public"."users_received_alerts" to "authenticated";

grant update on table "public"."users_received_alerts" to "authenticated";

grant delete on table "public"."users_received_alerts" to "service_role";

grant insert on table "public"."users_received_alerts" to "service_role";

grant references on table "public"."users_received_alerts" to "service_role";

grant select on table "public"."users_received_alerts" to "service_role";

grant trigger on table "public"."users_received_alerts" to "service_role";

grant truncate on table "public"."users_received_alerts" to "service_role";

grant update on table "public"."users_received_alerts" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."alerts"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."alerts"
as permissive
for select
to public
using (true);


create policy "Enable read for authenticated users only"
on "public"."alerts"
as permissive
for select
to authenticated
using (true);


create policy "Update only user's own"
on "public"."alerts"
as permissive
for update
to authenticated
using ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.id = alerts.user_id) AND ((u.auth_id)::text = (auth.uid())::text)))))
with check ((EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.id = alerts.user_id) AND ((u.auth_id)::text = (auth.uid())::text)))));


create policy "Enable insert for authenticated users only"
on "public"."alerts_verifications"
as permissive
for all
to authenticated
using (true)
with check (true);


create policy "Enable read access for all users"
on "public"."alerts_verifications"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."roles"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."tiers"
as permissive
for select
to public
using (true);


create policy "Enable delete for users based on user_id"
on "public"."users"
as permissive
for delete
to public
using ((( SELECT auth.uid() AS uid) = auth_id));


create policy "Enable insert for authenticated users only"
on "public"."users"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable select for authenticated users only"
on "public"."users"
as permissive
for select
to authenticated
using (true);


create policy "Enable all for authenticated users only"
on "public"."users_devices"
as permissive
for all
to authenticated
using (true)
with check (true);


create policy "Enable insert for authenticated users only"
on "public"."users_received_alerts"
as permissive
for all
to authenticated
using (true)
with check (true);


-- Ensure pg_net exists
create extension if not exists pg_net with schema extensions;

-- Trigger function
create or replace function public.notify_alert_status()
returns trigger
language plpgsql
as $$
begin
  perform net.http_post(
    url := 'https://alertly-backend-api-server.onrender.com/api/webhooks/alerts-status',
    body := jsonb_build_object(
      'type', TG_OP,
      'table', TG_TABLE_NAME,
      'schema', TG_TABLE_SCHEMA,
      'record', to_jsonb(NEW),
      'old_record', case when TG_OP = 'UPDATE' then to_jsonb(OLD) else null end
    ),
    headers := '{"Content-Type":"application/json"}'::jsonb,
    timeout_milliseconds := 5000
  );
  return NEW;
end;
$$;

-- Recreate trigger
drop trigger if exists alert_status on public.alerts;
create trigger alert_status
after insert or update on public.alerts
for each row
execute function public.notify_alert_status();
